### ISSUE TITLE
SearchGIFsAsync does not exist.

### ISSUE THREAD

**Issue by Badflar** [Yucked/GiphySharp#1]
I'm using the demo you show in the README but `await Client.SearchGIFsAsync` says the SearchFigsAsync does not exist under GiphyClient

**Comment by Yucked** [comment]
Hey.
The readme is a bit oudated but you'd need to access the `GIF` property on `GiphyClient` and use `SearchAsync` since it's part of the `GIF` class.

```cs
var client = new GIphyClient("");
var search = await client.Gifs.SearchAsync("");
```

**Comment by Badflar** [comment]
Oh I see. I got Giphy to work without the nuget anyways. Thanks though.
